name: Planetoid Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build for target x86_64-pc-windows-msvc
      working-directory: ./client
      run: cargo build

    - name: Run tests
      working-directory: ./client
      run: cargo test
