name: Planetoid Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build for target x86_64-pc-windows-msvc
      working-directory: ./client
      run: cargo build

    - name: Run tests
      working-directory: ./client
      run: cargo test

    - name: Prepare produced files
      run: |
        new-item -Name planetoid-windows -ItemType directory
        Copy-Item -Path "client\target\debug\planetoid.exe" -Destination "planetoid-windows"
        Copy-Item -Path "client\sounds" -Destination "planetoid-windows" -Recurse
        Compress-Archive -Path planetoid-windows -DestinationPath planetoid-windows.zip

    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Create a Github draft release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: winlatest
        title: Planetoid client Windows
        files: |
          planetoid-windows.zip
